# docker-compose.yml
version: "3.3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - '2701:2701'

  search_bot:
    build: ./bot
    depends_on:
      - mongodb
    links:
      - mongodb

  telegram_indexer:
    build: ./telegram_indexing
    depends_on:
      - mongodb
    links:
      - mongodb